name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

permissions:
  id-token: write
  contents: read
  pages: write  # Ensure Pages deployment permission is granted


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use the Node.js version compatible with your React app

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Upload build to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: client/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
